# Generated by Django 4.2.1 on 2023-05-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('auteur', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=255, upload_to='')),
                ('create_at', models.DateField()),
                ('updateDate', models.DateField()),
                ('tags', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
